### ISSUE TITLE
How to calculate the vp1 and vp2 for  camera calibration

### ISSUE THREAD

**Issue by EliasCai** [lhgiang149/final_project#1]
Hi~ Thank u for shareing project
I confused how you calculated vp1 and vp2 in file "Untitled1.ipynb"
```python
In [38]:
data = 'C:/Users/ADMINS/Desktop/SaiGon/foreign/video.avi'

vp1 = [1.136941176470588e+03,2.094117647058824e+02]
vp2 = [-1.842891566265060e+03,1.749397590361446e+02]
pp = [640,360]
scale = 0.009158282892303235
 ```
They are very important parameters for speed estimating.
And I guess u may inspired by this paper《Automatic Camera Calibration for Traffic Understanding》, but i can't find any code for referenced
So could u please show me the code, or give me some referenced?
Thank u very much!

**Comment by GiangHLe** [comment]
Hi @EliasCai , 
First, thank you for interesting about our project. I am really sorry because the code still look like a mess, I don't have enough time to clean code.
Second, for answer your question, 《Automatic Camera Calibration for Traffic Understanding》, correct series but wrong paper, take a look [this URL](https://medusa.fit.vutbr.cz/traffic/research-topics/traffic-camera-calibration/fully-automatic-roadside-camera-calibration-for-traffic-surveillance-ieee-its-2014/) it contain paper and matlab code for diamond space (calibration function).
Some tips: the input should be longer than 2 minutes and you should find big strange parallel road to get the best result. For more details, please read Markéta Dubská's paper.

**Comment by EliasCai** [comment]
Thank u for reply! @lhgiang149 , help me a lot!
I know nothing about Matlab and have no environment to run the program, 
but i have download the code and will try my best to figure out

**Comment by GiangHLe** [comment]
@EliasCai  Matlab's license is quite expensive, you can try on octave, it is an open source similar with matlab but i don't think it has enough necessary package.
There are many open source for camera calibration with C++ code. I can find [this link](https://github.com/ethz-asl/kalibr) with 1k4 stars. 
If you are satisfy with my answer, close this issues. Thank you!

**Comment by EliasCai** [comment]
u help me a lot!
all the best!
